name: FastCGM API CI

on:
  # workflow_dispatch:
  push:
    branches:
      - dev
    # paths:
      
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List files in the working directory
        run: ls -R
        
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      # To test in case of errors with pytest
      # - name: Run test with verbose output
      #   run: |
      #     pytest tests/test_database.py -xvs 2>&1 | tee test_output.log

      - name: Run Tests 
        run: |
          pytest tests/test_database.py -v > test_output.log    

      - name: Upload Test Results 
        uses: actions/upload-artifact@v4
        with: 
          name: test-results
          path: test_output.log
          retention-days: 1
        
  # Build:
  #   needs: Tests
  #   name: Docker Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
      
  #       - name: Docker Build
  #         run: docker build -t fast-cgm-api
         