name: FastCGM API CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - Dockerfile
      - main.py
      - tests/*
      - requirements.txt
      - database.py
      - models.py
      
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List files in the working directory
        run: ls -R
        
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      # To test in case of errors with pytest
      # - name: Run test with verbose output
      #   run: |
      #     pytest tests/ -xvs 2>&1 | tee test_output.log

      - name: Run Tests 
        run: |
          pytest tests/ -v > test_output.log    

      - name: Upload Test Results 
        uses: actions/upload-artifact@v4
        with: 
          name: test-results
          path: test_output.log
          retention-days: 1 
  Build:
    name: Docker Build and Trivy Scan
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fast-cgm-api:${{ github.sha }}
    
      - name: Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/${{ vars.DOCKERHUB_USERNAME }}/fast-cgm-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fast-cgm-api:${{ github.sha }}
  Update-Image-Manifest:
    name: Update K8s Manifest
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout K8s Manifests Repo
        uses: actions/checkout@v4
        with:
          repository: mauriquev/k8s-manifests
          token: ${{ secrets.MANIFEST_REPO_PAT }}
          ref: 'main'

      
      - name: Update Image Tag and Push
        run: |
          # Update image tag in deployment file
          sed -i "s|image: ${{ vars.DOCKERHUB_USERNAME }}/fast-cgm-api:.*|image: ${{ vars.DOCKERHUB_USERNAME }}/fast-cgm-api:${{ github.sha }}|g" fast-cgm-api/deployment.yaml
          
          # Configure git and push if there are changes
          git config --global user.name "${{ vars.GIT_USER_NAME }}"
          git config --global user.email "${{ vars.GIT_USER_EMAIL }}"
          git add fast-cgm-api/deployment.yaml
          git diff --staged --quiet || git commit -m "Update fast-cgm-api image to ${{ github.sha }}" && git push
            
        

      