name: FastCGM API CI

on:
  # workflow_dispatch:
  push:
    branches:
      - dev
    # paths:
      
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List files in the working directory
        run: ls -R
        
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt
      
      - name: Run tests 
        run: |
          pytest tests/ -v test_output.log

      # - name: Upload test results 
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: test-results
      #     path: test_output.log